GET http://localhost:3000/

###
// GET /users — возвращает всех пользователей
GET http://localhost:3000/users

###
// POST /users — создаёт пользователя
POST  http://localhost:3000/users

###
// GET /users/:userId - возвращает пользователя по _id
GET http://localhost:3000/users/62586a743a024449d70a1ecd
###
// GET /users/:userId - возвращает пользователя по не корректному  _id
GET http://localhost:3000/users/52586a743a024449d70a1ecd
###
// GET /users/:userId - возвращает пользователя по не сущест  _id
GET http://localhost:3000/users/62586a743a024449d70a1e

###
// GET /users/:userId - возвращает пользователя по не правильному _id
GET http://localhost:3000/users/62586a743a024449d

###
// GET /cards — возвращает все карточки
GET http://localhost:3000/cards

###
// PUT /cards/:cardId/likes — поставить лайк карточке
PUT http://localhost:3000/cards/62595c7bec9875d7f8b9139f/likes

###
PATCH http://localhost:3000/users/me/avatar