GET http://localhost:3000/

###
// GET /users — возвращает всех пользователей
GET http://localhost:3000/users

###
// POST /users — создаёт пользователя
POST  http://localhost:3000/users

###
// GET /users/:userId - возвращает пользователя по _id
GET http://localhost:3000/users/62591d4c839c04440ae7b953

###
// GET /cards — возвращает все карточки
GET http://localhost:3000/cards

###
// PUT /cards/:cardId/likes — поставить лайк карточке
PUT http://localhost:3000/cards/62595c74ec9875d7f8b9139d/likes